enum ActionType {
  SELL_CARDS,
  BUILD_FACTORY,
  BUILD_CITY,
  BUILD_FOREST_WITH_MC,
  BUILD_OCEAN,
  ASTEROID,
  INCREASE_TEMPERATUR,
  BUILD_FOREST_WITH_CROP,
  BUY_CARDS,
  PLAY_CARDS_WITH_MC,
  PLAY_CARDS_WITH_STEEL,
  PLAY_CARDS_WITH_TITAN
}

